app = 'video-messenger-backend'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'
  MEDIASOUP_MIN_PORT = '10000'
  MEDIASOUP_MAX_PORT = '10100'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 10000

  [[services.ports]]
    port = 10000

[[services]]
  protocol = 'udp'
  internal_port = 10010

  [[services.ports]]
    port = 10010

[[services]]
  protocol = 'udp'
  internal_port = 10020

  [[services.ports]]
    port = 10020

[[services]]
  protocol = 'udp'
  internal_port = 10030

  [[services.ports]]
    port = 10030

[[services]]
  protocol = 'udp'
  internal_port = 10040

  [[services.ports]]
    port = 10040

[[services]]
  protocol = 'udp'
  internal_port = 10050

  [[services.ports]]
    port = 10050

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
